@echo off
echo 正在启动 PekHight VPN 服务器...

echo 步骤1: 启用路由和IP转发...
powershell -ExecutionPolicy Bypass -File enable_routing.ps1

echo 步骤2: 配置Internet连接共享...
powershell -ExecutionPolicy Bypass -File enable_ics.ps1

echo 步骤3: 启动VPN服务器...
pekserver.exe -port 23456 -enable-reg

pause
