@echo off
echo 正在启动 PekHight VPN 服务器（无RRAS版本）...

echo 步骤1: 启用IP转发...
powershell -ExecutionPolicy Bypass -Command "Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters' -Name 'IPEnableRouter' -Value 1"

echo 步骤2: 配置简易NAT...
powershell -ExecutionPolicy Bypass -File simple_nat.ps1

echo 步骤3: 启动VPN服务器...
pekserver.exe -port 23456 -enable-reg -skip-ip-forward-check=true

pause
